# Generated by Django 5.2.1 on 2025-06-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute_value',
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
