# Generated by Django 5.2.1 on 2025-06-14 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_attributekey_attributevalue_attribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name_plural': 'Attribute Products'},
        ),
        migrations.AlterModelOptions(
            name='attributekey',
            options={'verbose_name_plural': 'Attribute Keys'},
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'verbose_name_plural': 'Attribute Values'},
        ),
        migrations.AlterField(
            model_name='attribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='shop.product'),
        ),
    ]
